namespace FullStack.API.Models
{
    public class Employee
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public long Phone { get; set; }
        public long Salary { get; set; }
        public string Department { get; set; }
    }
}
/*
 * The GUID data type is a 16 byte binary data type. 
 * This data type is used for the global identification of 
 * objects, programs, records, and so on. The important property 
 * of a GUID is that each value is globally unique. 
 * The value is generated by an algorithm, developed by 
 * Microsoft, which assures this uniqueness.
 * 
 * You can annotate a property directly as non-nullable.
 * public string Property{ get; set; } = null!;
 */